name = "zsh-site"
main = "workers-site/index.js"
compatibility_date = "2024-01-01"
account_id = "09249c50fffa4a63949e85d627f4ff16" # <-- Add your Account ID here

[site]
bucket = "./dist"

[[kv_namespaces]]
binding = "__STATIC_CONTENT"
id = "53698c999643497cb8409723f3a2f501" # <-- Add your KV Namespace ID here
preview_id = "53698c999643497cb8409723f3a2f501"